#!/usr/bin/env bash

. colors

if [[ $# == 0 ]]; then
    c.header 'review requested:'
    gh pr list -S review-requested:@me;
    c.header 'no review:'
    gh pr list -S review:none;
    c.header 'approved, not merged:'
    gh pr list -S review:approved;
    c.header 'review changes requested:'
    gh pr list -S review:changes_requested;
    c.header 'other:'
    gh pr list -S '-review:none -review:approved -review-requested:@me -review:changes_requested';
    exit 1;
fi

git status
c.askContinue "Continue";


prNumber=$1
repoOwner=`gh pr view $prNumber --json headRepositoryOwner --jq .headRepositoryOwner.login`
branch=`gh pr view $prNumber --json headRefName --jq .headRefName`
branchTo=`gh pr view $prNumber --json baseRefName --jq .baseRefName`

gup $branchTo

git fetch $repoOwner

c.header "git merge $repoOwner/$branch --no-ff --no-commit"
git merge $repoOwner/$branch --no-ff --no-commit
